# GHA workflow and pkgdev package courtesy of @dieghernan
# Unaltered workflow example: https://github.com/dieghernan/pkgdev/blob/main/.github/workflows/update-docs.yaml

on:
  push:
    paths: ['README.Rmd']
  workflow_dispatch:

name: update-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::rcmdcheck
            any::reactable
            ropengov/rogtemplate
            dieghernan/pkgdev
          needs: website

      - name: Update README and .cff file
        run: |

          pkgdev::update_docs(pkg = ".", url_update = FALSE, create_codemeta = FALSE, create_cff = TRUE, build_readme = TRUE, verbose = FALSE, precompute = FALSE)

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'Update docs with pkgdev' || echo "No changes to commit"
          git push origin || echo "No changes to commit"